const ACRONYMS = {'AFK': 'Away from keyboard',
                  'BRB': 'Be right back',
                  'LOLZ': 'Laugh out loud (with a lot emphasis)' ,
                  'TLDR': 'Too long did not read',
                  'GTG': 'Got to go',
                  'TOTES': 'Totally',
                  'LMK': 'Let me know',
                  'RN': 'Right now',
                  'BID': 'Break it down',
                  'COB': 'Close of business',
                  'EOD': 'End of day',
                  'EOM': 'End of message',
                  'EOT': 'End of thread',
                  'EOW': 'End of week',
                  'ETA': 'Estimated time of arrival',
                  'FTE': 'Full-time employee',
                  'FWIW': 'For what it’s worth',
                  'IAM': 'In a meeting',
                  'IMO': 'In my opinion',
                  'KISS': 'Keep it simple stupid',
                  'LET': 'Leaving early today',
                  'LMK': 'Let me know',
                  'MoM': 'Month over month',
                  'MTD': 'Month to date',
                  'NIM': 'No internal message',
                  'OOO': 'Out of office',
                  'OT': 'Off topic',
                  'OTP': 'On the phone',
                  'PA': 'Performance appraisal',
                  'POC': 'Point of contact',
                  'PTE': 'Part-time employee',
                  'PTO': 'Paid time off',
                  'NRN': 'No reply necessary',
                  'NSFW': 'Not safe for work',
                  'NWR': 'Not work related',
                  'Re': 'Referring to',
                  'RFD': 'Request for discussion',
                  'SME': 'Subject matter expert',
                  'TED': 'Tell me, explain to me, describe to me',
                  'TL;DR': 'Too long, didn’t read',
                  'TLTR': 'Too long to read',
                  'TOS': 'Terms of service',
                  'TYT': 'Take your time',
                  'WFH': 'Work from home',
                  'WIIFM': 'What’s in it for me',
                  'WOM': 'Word of mouth',
                  'YTD': 'Year to date',
                  'ACCT': 'Account',
                  'AP': 'Accounts payable',
                  'AR': 'Accounts receivable',
                  'BS': 'Balance sheet',
                  'CR': 'Credit',
                  'DR': 'Debit',
                  'EPS': 'Earnings per share',
                  'FIFO': 'First in, first out',
                  'LIFO': 'Last in, first out',
                  'LWOP': 'Leave without pay',
                  'NAV': 'Net assets value',
                  'P-card': 'Purchase card',
                  'ROA': 'Return on assets',
                  'ROE': 'Return on equity',
                  'P&L': 'Profit and loss',
                  'PM': 'Direct message me',
                  'AIDA': 'Attention, interest, desire, action',
                  'B2B': 'Business to business',
                  'B2C': 'Business to consumer',
                  'BR': 'Bounce rate',
                  'CMS': 'Content management system',
                  'CPC': 'Cost per click',
                  'CTA': 'Call to action',
                  'CTR': 'Click through rate',
                  'CR': 'Conversion rate',
                  'CRM': 'Customer relationship management',
                  'DM': 'Direct message or direct mail',
                  'ESP': 'Email service provider',
                  'GA': 'Google Analytics',
                  'KPI': 'Key performance indicator',
                  'PPC': 'Pay per click',
                  'PV': 'Page view',
                  'RFP': 'Request for proposal',
                  'ROS': 'Run of site',
                  'RT': 'Retweet',
                  'SAAS': 'Software as a service',
                  'SM': 'Social media',
                  'SMB': 'Small to medium business',
                  'SWOT': 'Strengths, weaknesses, opportunities, threats',
                  'UV': 'Unique visitor',
                  'BD': 'Business development',
                  'CSR': 'Corporate social responsibility',
                  'CFP': 'Certified financial planner',
                  'DOE': 'Depending on experience',
                  'GC': 'General counsel',
                  'HR': 'Human resources',
                  'PM': 'Project manager'
                }

module.exports = ACRONYMS;
